### ISSUE TITLE
Dont work on Ubuntu 14.04

### ISSUE THREAD

**Issue by EugeneBogun** [Lazy-Newb-Pack/LNP-Linux-legacy#11]
Hello
When start game it has error
 ./startlnp 
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 41, in **init**
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 89, in detect_basedir
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/posixpath", line 369, in abspath
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 13: ordinal not in range(128)

P.S
Problem was in russian letters in folder name
I resolve it change folder name

**Comment by novgosh** [comment]
Same problem on Ubuntu 14.04

**Comment by fricy** [comment]
Forwarded bugreport [@launcher bugtracker](https://bitbucket.org/Pidgeot/python-lnp/issue/47/problem-with-russian-language)

**Comment by Pidgeot** [comment]
Non-ASCII folder names are likely to cause issues since Python 2 is not fully Unicode, and there is, to my knowledge, no good way of building stand-alone executables using Python 3.

**Comment by fricy** [comment]
Catching the exception and displaying an instruction to use only standard english? letters in the folder name would be a partial solution though.

**Comment by Pidgeot** [comment]
For the next PyLNP build I'll be adding this message when that particular error occurs:

> ERROR: PyLNP is being stored in a path containing non-ASCII characters, and cannot continue. Folder names may only use the characters A-Z, 0-9, and basic punctuation.

Issues may still occur if DF itself is in a path with non-ASCII characters; if I can narrow down a good place to catch that, I'll see if I can add a message to that case.

ETA on a release with this change is some time in January - unfortunately, I can't be more precise at this point.

**Comment by BeauBouchard** [comment]
I also received a similar error

   # File "", line 11, in 
   # File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 41, in init

 when I tried to install the package on ubuntu fresh install, it goes away when you install the  [dependencies](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#dependencies) specifically I think its unicode-16 characters in a unicode-8 environment such as in binary filenames. But it completely works after the silly large list of dependencies are installed. Not sure 

 I need to revise the list as some of them are no longer needed, like QT5.
