### ISSUE TITLE
Undefined symbol error

### ISSUE THREAD

**Issue by mensinda** [Lazy-Newb-Pack/LNP-Linux-legacy#14]
Trying to start dwarf fortress from LNP results in this error:

```
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
```

Tested Versions: 0.40.23 and 0.40.24
System: Arch Linux 64 bit

Launching DF from the comand line works if I remove all *.so from the libs folder and copy the Arch Linux lib libgraphics.so into it. Sadly this does not solve the symbol error described above.

**Comment by BeauBouchard** [comment]
Thank you very much for taking the time to fill out an issue report. 

I think I do have one thing you can try. does it work when you [Downgrade to bash](http://www.gnu.org/software/bash/manual/bashref.html#Installing-Bash) [4.2](http://ftp.gnu.org/gnu/bash/) from 4.3?

**Comment by mensinda** [comment]
Downgrading bash "fixed" the problem but now I have a different problem with dfhack:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Loading bindings from data/init/interface.txt
New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

Resetting textures
Can't load plugin <path/to/DF>/04024r1-x64/df_linux/hack/plugins/stonesense.plug.so
TWBT: version 5.42
TWBT: set PRINT_MODE to TWBT or TWBT_LEGACY in data/init/init.txt to activate the plugin
Enabled tweak stable-cursor (stable_cursor_hook::feed)
Enabled tweak advmode-contained (advmode_contained_hook::feed)
Enabled tweak fast-trade (fast_trade_assign_hook::feed)
Enabled tweak fast-trade (fast_trade_select_hook::feed)
Enabled tweak military-stable-assign (military_assign_hook::feed)
Enabled tweak military-color-assigned (military_assign_hook::render)
Enabled tweak craft-age-wear (craft_age_wear_hook::ageItem)
Enabled tweak farm-plot-select (farm_select_hook::feed)
Enabled tweak farm-plot-select (farm_select_hook::render)
Enabled tweak import-priority-category (takerequest_hook::feed)
Enabled tweak import-priority-category (takerequest_hook::render)
Enabled tweak civ-view-agreement (civ_agreement_view_hook::render)
Stockflow is now enabled.
multilevel is not a recognized command.
multilevel is not a recognized command.
DFHack is ready. Have a nice day!
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]# 
```

This error also occurs also when I start DF directly with the dfhack script.

**Comment by mensinda** [comment]
Sorry wrong button...

**Comment by lethosor** [comment]
What exactly is the problem there?

**Comment by BeauBouchard** [comment]
that looks like it works

**Comment by mensinda** [comment]
It cant load stonesense. I do not need or use this plugin but it seams to be a bug.

**Comment by lethosor** [comment]
Is there anything in stderr.log?

**Comment by mensinda** [comment]
No. Both log files are empty.

**Comment by lethosor** [comment]
They shouldn't be empty. Try launching DF again and search for any Stonesense-related messages in stderr.log.

**Comment by mensinda** [comment]
Found the problem: I had to remove the libs directory in df_linux/hack and install allegro.
