### ISSUE TITLE
qfconvert doesn't appear in utility list

### ISSUE THREAD

**Issue by sethwoodworth** [Lazy-Newb-Pack/LNP-Linux-legacy#15]
Is it always running? Adding it to include.txt didn't seem to change anything.

Is this a bug? Is this expected?

Also, when I go to the dfhack tab, there are no hacks listed to enable.  I'm not sure if there should be items in the list.

**Comment by BeauBouchard** [comment]
Hello and thank you for taking the time to fill out an issue report. 

qfconvert  or rather Quick Fort is a tool which converts between images and CSV into a macro file which is to be used with Dwarf fortress. qfconvert is a python script with no GUI and will not show up as its own window. The tool is a more advanced utility which only comes with [support and instructions from it's owner's website](http://www.joelpt.net/quickfort/#linuxosx-quick-start). 

Below are the basic instructions to getting the utility to work on linux: 

You must have Python 2.6.4 installed.

Run the command line conversion tool via python:

> cd pack/LNP/utilities/qfconvert
> python ./qfconvert.py
> or chmod +x qfconvert.py and run it like a shell script.

Examples:

> python ./qfconvert.py --info myblueprint.xls
>   (..information about myblueprint.xls..)
> 
> python ./qfconvert.py myblueprint.xls <DF folder>/data/init/macros/foo.mak

Although I do keep the utility in the package still I recommend using the more modern DFHack script [DigFort](https://github.com/DFHack/dfhack#digfort) It operates nearly identically as Quick Forts however it is built into DFHack. 

As far as the hacks under the DFhack tab, [Pidgeot's PyLNP 0.8b Lazy Newb Pack Python interface](https://bitbucket.org/Pidgeot/python-lnp/overview) is very very new still, many of these features such as the utilities window and the [DFhack window](https://bitbucket.org/Pidgeot/python-lnp/overview#rst-header-dfhack) are great new features however under utilized by myself as it is difficult testing N number of configurations on each Distro on each architecture. 

If you have something you would like to show up in the default configurations for DFhack or any suggestions for the LNP linux, please let us know in the [forum thread](http://www.bay12forums.com/smf/index.php?topic=140966.0) or come see me on freenode ( Beautato ) .

**Comment by lethosor** [comment]
I believe that Python 2.7 should work as well, although I haven't checked.

**Comment by sethwoodworth** [comment]
Yes, I have this running with python 2.7 now.

I'm looking into extending digfort to support more designate/build types.  The digfort ruby script is much cleaner, but doesn't support everything I want.
