### ISSUE TITLE
QT5 GCC 4.9.1 startlnp broken

### ISSUE THREAD

**Issue by kahrkunne** [Lazy-Newb-Pack/LNP-Linux-legacy#2]
Line 14 says "py PyLNP.py"
There's multiple things wrong with this:
- First of all, there is no "py" command, I think you mean python
- Second of all, there is no PyLNP.py file, I think you mean PyLNP 
- Third of all, PyLNP is a binary file and not a python file

**Comment by BeauBouchard** [comment]
yep, sorry an alias / something else I was working on got into the build :-1:  on me, the startup file should be as so: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/startlnp,  thank you for bringing this to my attention.

**Comment by BeauBouchard** [comment]
0.40.13.r1.d491qt5 , 0.40.13.r1.p491qt5 releases both had the problem, I fixed them and the downloads on the website did not have the same problem, only the github release.
