### ISSUE TITLE
storing large binaries in a git repo will someday backfire

### ISSUE THREAD

**Issue by miffedmap** [Lazy-Newb-Pack/LNP-Linux-legacy#21]
every release grows the repo by ~15MB or so and soon enough working with the repo
will be a big pain. GH releases are better for hosting binaries, the repo itself should
preferably contain just the recipes for bootstrapping the preparation of a new release.

@BeauBouchard, I've made this mistake before - just trying to save you some pain.

**Comment by BeauBouchard** [comment]
You're right.

**Comment by BeauBouchard** [comment]
Originally It was just the critical files which I would add in when assembling the package.  I can get rid of all the crud, knock out some of the larger compiled binaries and the graphics packages since they are very large and mainly are from fricy/DFgraphics. What else would you suggest?

**Comment by miffedmap** [comment]
just that it would be nice if you check-in the release scripts or a checklist (whatever you use) for doing the releases. though ofcourse that's up to you.

**Comment by BeauBouchard** [comment]
:+1: Thanks! I will better document what I am doing in the wiki I sort of started for the [package update checklist](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/wiki/Package-update-Instructions); that should be a good start.

Also, hop on our IRC some time [#lazynewbpack](http://webchat.freenode.net/?channels=%23lazynewbpack).  You can always get a message  to me  there about any changes, even if you want to request something.

**Comment by miffedmap** [comment]
Thanks. I guess we can close this.
