### ISSUE TITLE
distro_fixes.sh should support gentoo

### ISSUE THREAD

**Issue by miffedmap** [Lazy-Newb-Pack/LNP-Linux-legacy#23]
`distro_fixes.sh` takes care of distro-specific adjustments in order to run df, specifically
a known issue when running df (which is 32 bit) on 64 bit distros having to do with libz which manifests 
as bogus "file not found" errors. 
fedora support is already there, but gentoo support isn't yet.
https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/1#issuecomment-76594113.

@ald0n, let's take care of required changes to `distro_fixes.sh` here. also, are you comfortable with bash scripts and git/github, if so can you make a pull-request with the required changes to `distro_fixes.sh`, the comments there should be all you need. 
if not, can you tell me what is the path for the default install of the 32bit version of `libz.so.1` on gentoo?

**Comment by ald0n** [comment]
> are you comfortable with bash scripts and git/github

don't, but i can try at least.

> can you tell me what is the path for the default install of the 32bit version of libz.so.1 on gentoo?

lrwxrwxrwx 1 root root  13 Oct 23 05:06 /lib32/libz.so.1 -> libz.so.1.2.8
-rwxr-xr-x 1 root root 90K Oct 23 05:06 /lib32/libz.so.1.2.8

Also, look at http://data.gpo.zugaina.org/eroen/games-simulation/dwarffortress/dwarffortress-40.24.ebuild eroen's ebuild, which works perfectly.

UPD:
Now it works with **LD_PRELOAD=/lib32/libz.so.1 ./df**

**Comment by miffedmap** [comment]
Please check if the changes to the script in #24 work?

**Comment by ald0n** [comment]
with new *distro_fixes.sh* i got
**./df** or **./dfhack**
> [distro_fixes.sh] you must provide DF_DIR as an argument.

I also changed paths in df
>PRELOAD_LIB="/lib32/libz.so.1 ./hack/libdfhack.so"

and in dfhack
>PRELOAD_LIB="/lib32/libz.so.1:./hack/libdfhack.so"

This working with previous distro_fixes.sh

**Comment by ald0n** [comment]
with new _distro_fixes.sh_ i got
**./df** or **./dfhack**

> [distro_fixes.sh] you must provide DF_DIR as an argument.

I also changed paths in df

> PRELOAD_LIB="/lib32/libz.so.1 ./hack/libdfhack.so"

and in dfhack

> PRELOAD_LIB="/lib32/libz.so.1:./hack/libdfhack.so"

This working with previous distro_fixes.sh

**Comment by miffedmap** [comment]
you need to grab the PR branch to pick up changes from #20 which was merged yesterday.

it's good you've got it working but we need to make sure it works out of the box so other gentoo users benefit from your help.
