### ISSUE TITLE
Arch Linux: Error when launching from GUI

### ISSUE THREAD

**Issue by ghost** [Lazy-Newb-Pack/LNP-Linux-legacy#28]
Clicking "Play Dwarf Fortress!" from the GUI results in a pop-up saying "Not found: data/art/Phoebus_16x16.png". Running df from the command line works since the fixes dealing with zlib for Arch Linux have been pushed. The GUI, however, appears to ignore those fixes. 

System: Arch Linux 64-bit
Also using Pidgeot's latest PyLNP.

**Comment by miffedmap** [comment]
Thanks, PR is up.
