### ISSUE TITLE
Graphics install problems and wrong TwbT version

### ISSUE THREAD

**Issue by PeridexisErrant** [Lazy-Newb-Pack/LNP-Linux-legacy#32]
Just passing along http://redd.it/2ztxxn

**Comment by lethosor** [comment]
> i tried to replace all the raw, data files in the folders manually and its almost work but the dwarves tiles stucks with the phoebius tileset

This part sounds a lot like a PyLNP issue.

**Comment by BeauBouchard** [comment]
this only happens in PyLNP 0.9.4, and is fixed with the newest version of PyLNP 0.9.5a. Also PyLNP 0.9.5a is pretty awesome! :+1: :+1:

**Comment by PeridexisErrant** [comment]
Re: TWBT - you need v5.43, not the official release .42; the latter is not compatible with DFHack 40.24-r2

**Comment by BeauBouchard** [comment]
:+1: thanks for the info. I will be using v5.43 from  http://do1.mifki.com:8810/dashboard;jsessionid=g2dj1d13cw7q1o5v7tgm5v8i8
