### ISSUE TITLE
PyLNP not opening [2]

### ISSUE THREAD

**Issue by ghost** [Lazy-Newb-Pack/LNP-Linux-legacy#34]
I'm having the same issue as described in #7 .

terminal output:

> ./PyLNP: 1: ./PyLNP: ����%ڕ!h: not found
> ./PyLNP: 1: ./PyLNP: NB]K: not found
> ./PyLNP: 1: ./PyLNP: 9^@WRVM[
>                                SOZEL
>                                      : not found
> ./PyLNP: 1: ./PyLNP: FA_71X4:/: not found
> ./PyLNP: 1: ./PyLNP: �ah�ap�ax�a��a��a��a: not found
> ��a��a��a��aȲaвaزa��a��a��a��a�a�a�a�a: not found
> ./PyLNP: 1: ./PyLNP: �aJh�aKp�aLx�aM��aN��aO��aP��aQ��aR��aS��aU��aV��aWȴaXдaYشaZ��a[��a]��a^��a_�a: not found
> ./PyLNP: 1: ./PyLNP: ����%ږ!h: not found
> ./PyLNP: 2: ./PyLNP: �@����%ʖ!h
>                                �0����%!h
>                                          �: not found
> ./PyLNP: 1: ./PyLNP: cannot create �@@x�@@'$@@@@@��@@@@ԯԯ ��a�Q�td/lib64/ld-linux-x86-64.so.2GNU GNUc*�Ž5�}2~x�'�CaYH56(T.Q� 6�*���ص�n���>��IA��Zz��a�@��p��f�a�е��C�60�J���Y����[u�Ga�����a+>�n;��tJ�$f��B�
>                                             �|0������a����������:b2T�7libdl.so.2dlsymdlerrordlopenlibz.so.1inflateEndinflatezlibVersioninflateInit_libm.so.6sqrtlibc.so.6tolowergetenvfwritetouppermemcpystpcpyreallocvfprintfreadlinkstrcatfeofrealpathremovermdirstrcasecmpmkdtempmkdirmallocstrrchrstrlenopendir_IO_stdin_usedexecvstrncasecmpfdopensetbufwaitgetpidstdoutmemmovefclosefreadstrncatfopenfgetcstderrstrtok__libc_start_mainfilenovprintfclosedir__xpg_basenamefputcfgetsferrorstrncpyunsetenvunlinkfflushmemsetqsortmkstempmemcmpvsnprintfsprintfclearerrstdinfseekexitrenameforkraisestrstrstrcmpftellfreereaddirstrchrfchmodisspacestrdupntohlexecvpsignalstrcpykill__xstat_edata__bss_start_end__gmon_start__native_linker_pathlsb_linker_pathGLIBC_2.2.5GLIBC_2.3uii	� �a(�a	�fii
>                           0�a��a8�a%��a
>                                            ��a.X�a�a(h�a)p�a*x�a+��a,��a-��a/��a0��a1��a2��a3��a4��a5ȳa6гa7سa8��a9��a:��a<��a=�a�a?�a@�aA �aB(�aC0�aD8�aE@�aFH�aGP�aHX�aIH���H���5�!�%$�!@�%�!h������%�!h������%�!h������%
> �!h������%�!h������%��!h������%��!h������%��!h�p����%��!�����%Z�!h�P����%R�!h�@����%J�!h�0����%B�!h� ����%:�!h�����%2�!h�����%*�!h������%�!h: Directory nonexistent
> ./PyLNP: 1: ./PyLNP: ELF: not found
> ./PyLNP: 8: ./PyLNP: Syntax error: "(" unexpected

distro: lubuntu 17.10, 32bit
lnp version: LNP-Linux-legacy-0.40.24.r3.c454qt4

**Comment by lethosor** [comment]
Did you figure it out?

**Comment by ghost** [comment]
No, but I downloaded the separate PyLNP from bitbucket repo (https://bitbucket.org/Pidgeot/python-lnp/downloads/PyLNP_0.13b-linux-i686.tar.xz) and it worked, but due to unrelated reasons I don't use it now, so I can't provide much detail.

**Comment by lethosor** [comment]
I'm guessing the issue was that you were using the 64-bit launcher on a 32-bit system, then. That output looks like what I've seen from other people who've done that.
