### ISSUE TITLE
xdg-terminal: configured terminal program 'rxvt-unicode' not found or not executable

### ISSUE THREAD

**Issue by suhr** [Lazy-Newb-Pack/LNP-Linux-legacy#5]
Subj. No matter what `$TERM` is set:

`
% TERM=xterm ./startlnp 
xdg-terminal: configured terminal program 'xterm' not found or not executable
`

Version: v0.40.13r1.p491qt5

**Comment by BeauBouchard** [comment]
Thank you for reporting the issue, if you don't mind me asking what Distro  / Distro version are you using?

**Comment by suhr** [comment]
Sabayon Linux (Gentoo-like distro).

**Comment by BeauBouchard** [comment]
Thank you again, The lazy newb pack for Gentoo has a patch for it https://raw.githubusercontent.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/master/pack/LNP/utilities/gentoopatch/gentoopatch.sh and possibly using https://github.com/svenstaro/dwarf_fortress_unfuck . I also recommend trying the latest release, i pushed a little bit ago

**Comment by suhr** [comment]
Looks like it's a PyLNP issue, not df itself. But latest release actually fixes this, thanks!

**Comment by suhr** [comment]
PS: there's also known df bug on gentoo: http://www.bay12games.com/dwarves/mantisbt/view.php?id=2688. Consider setting LD_PRELOAD by PyLNP.

**Comment by BeauBouchard** [comment]
I will take that under consideration thank you for the followup and additional information. :cake:
