### ISSUE TITLE
PyLNP not opening

### ISSUE THREAD

**Issue by Jay-Roden** [Lazy-Newb-Pack/LNP-Linux-legacy#7]
All of this is directly from the terminal:

./PyLNP: 1: ./PyLNP: ����%ڕ!h: not found
./PyLNP: 1: ./PyLNP: NB]K: not found
./PyLNP: 1: ./PyLNP: 9^@WRVM[
                               SOZEL
                                     : not found
./PyLNP: 1: ./PyLNP: FA_71X4:/: not found
./PyLNP: 1: ./PyLNP: �ah�ap�ax�a��a��a��a: not found
��a��a��a��aȲaвaزa��a��a��a��a�a�a�a�a: not found
./PyLNP: 1: ./PyLNP: �aJh�aKp�aLx�aM��aN��aO��aP��aQ��aR��aS��aU��aV��aWȴaXдaYشaZ��a[��a]��a^��a_�a: not found
./PyLNP: 1: ./PyLNP: ����%ږ!h: not found
./PyLNP: 2: ./PyLNP: �@����%ʖ!h
                               �0����%!h
                                         �: not found
./PyLNP: 1: ./PyLNP: cannot create �@@x�@@'$@@@@@��@@@@ԯԯ ��a�Q�td/lib64/ld-linux-x86-64.so.2GNU GNUc_�Ž5�}2~x�'�CaYH56(T.Q� 6�_���ص�n���>��IA��Zz��a�@��p��f�a�е��C�60�J���Y����[u�Ga�����a+>�n;��tJ�$f��B�
                                            �|0������a����������:b2T�7libdl.so.2dlsymdlerrordlopenlibz.so.1inflateEndinflatezlibVersioninflateInit_libm.so.6sqrtlibc.so.6tolowergetenvfwritetouppermemcpystpcpyreallocvfprintfreadlinkstrcatfeofrealpathremovermdirstrcasecmpmkdtempmkdirmallocstrrchrstrlenopendir_IO_stdin_usedexecvstrncasecmpfdopensetbufwaitgetpidstdoutmemmovefclosefreadstrncatfopenfgetcstderrstrtok__libc_start_mainfilenovprintfclosedir__xpg_basenamefputcfgetsferrorstrncpyunsetenvunlinkfflushmemsetqsortmkstempmemcmpvsnprintfsprintfclearerrstdinfseekexitrenameforkraisestrstrstrcmpftellfreereaddirstrchrfchmodisspacestrdupntohlexecvpsignalstrcpykill__xstat_edata__bss_start_end__gmon_start__native_linker_pathlsb_linker_pathGLIBC_2.2.5GLIBC_2.3uii  � �a(�a    �fii
                          0�a��a8�a%��a
                                           ��a.X�a�a(h�a)p�a_x�a+��a,��a-��a/��a0��a1��a2��a3��a4��a5ȳa6гa7سa8��a9��a:��a<��a=�a�a?�a@�aA �aB(�aC0�aD8�aE@�aFH�aGP�aHX�aIH���H���5�!�%$�!@�%�!h������%�!h������%�!h������%
�!h������%�!h������%��!h������%��!h������%��!h�p����%��!�����%Z�!h�P����%R�!h�@����%J�!h�0����%B�!h� ����%:�!h�����%2�!h�����%_�!h������%�!h: Directory nonexistent
./PyLNP: 1: ./PyLNP: ELF: not found
./PyLNP: 8: ./PyLNP: Syntax error: "(" unexpected

**Comment by BeauBouchard** [comment]
Thank you for taking the time give feedback. 

if you don't mind answering a few questions I would be happy to help. 

Which Version of Lazy Newb Pack you were using?

Which Linux Distro are you using and which version?

Does the application work or show any signs of working?

Thanks again

**Comment by Jay-Roden** [comment]
I'm using:
LNP-PyLNP-linux-v0.40.16r1.p454qt5 (I also tried directly downloading if from this git repo and i got the same thing,)
Linux Mint Qiana 17
And no

**Comment by Jay-Roden** [comment]
If there is anyway I can get it working It would be awsome since this is my only way to play DF.

**Comment by BeauBouchard** [comment]
Alright, still trying to think of what could be wrong, if you don't mind answering a few more questions, Are you on a 32 or a 64 bit architecture? 

And [have you installed all the dependencies](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#dependencies)? 

```
sudo apt-get install default-jre libsdl1.2debian:i386 libsdl-image1.2:i386 libsdl-ttf2.0-0:i386 libglu1-mesa:i386 libgtk2.0-0:i386 libopenal1:i386 libjpeg62:i386 git mercurial wget coreutils tar unzip unrar make g++ gcc patch xterm sed python bzip2 qtchooser qtbase5-dev qtbase5-dev-tools qtscript5-dev qt5-qmake libqt5script5 libqt5scripttools5 libqxt-core0 libqxt-gui0
```

Update: 

Also, are you launching the application from the PyLNP? It would be best to start the application using the  script ./[startlnp](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/startlnp)

**Comment by Jay-Roden** [comment]
If I remeber correctly 32 bit, it's been a year at least since I installed it, and yes I have.

Relpy to Update: Yes that is how i found out PyLNP had a bug.

**Comment by Jay-Roden** [comment]
If there is a way I can use a share screen program with you to show you things that don't work than i can do that.

**Comment by BeauBouchard** [comment]
"LNP-PyLNP-linux-v0.40.16r1.p454qt5" the one you were using is the x64 bit version of the package. The launcher is meant for 64bit architecture, [try this one](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/releases/tag/0.40.16.r1.d454qt5), it should have the 32 bit/i686 version of the PyLNP. Run the application using the script "startlnp".   Let me know how it works.

**Comment by Jay-Roden** [comment]
I have the same bug.

I would be willling to do teamviewer with you if you think it would help.

**Comment by Jay-Roden** [comment]
I was unable to locat/find some of the packages.

**Comment by BeauBouchard** [comment]
> I would be willing to do teamviewer with you if you think it would help. 

that is a dangerous thing to do with a stranger :D 

 I installed Linux Mint 17 "Qiana" - Cinnamon (32-bit) on my laptop and was able to get LNP to work after running these 3 commands in terminal. First open up terminal then use the commands:

```
sudo apt-get update
sudo apt-get upgrade      
```

you may need to type "y" or "i" to approve new upgrades at that point. 

Then I installed the dependencies  

```
sudo apt-get install default-jre libsdl1.2debian:i386 libsdl-image1.2:i386 libsdl-ttf2.0-0:i386 libglu1-mesa:i386 libgtk2.0-0:i386 libopenal1:i386 libjpeg62:i386 git mercurial wget coreutils tar unzip unrar make g++ gcc patch xterm sed python bzip2 qtchooser qtbase5-dev qtbase5-dev-tools qtscript5-dev qt5-qmake libqt5script5 libqt5scripttools5 libqxt-core0 libqxt-gui0
```

Then I [downloaded the correct LNP](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/releases/tag/0.40.16.r1.d454qt5) and then ran the startlnp script from the download. the LNP GUI shows up and DF works fine, but not with DFhack. 

What command exactly are you using to start the application?

**Comment by Jay-Roden** [comment]
sudo apt-get install update is not a command for me, nether is upgrade. But i did the equivelent of thows commands and tried installing all the packages again and nothing.
I'm using "./startlnp"

Also it woudn't be that dangerous since you would need the root/admin password to do any real harm.

**Comment by BeauBouchard** [comment]
sorry, i mistyped, its:

```
sudo apt-get update
sudo apt-get upgrade      
```

**Comment by Jay-Roden** [comment]
Yes i tried them and nothing needed to be updated/upgraded (I do updates and upgrades nightly)

If i may be so bold to ask, can i add you on skype?

**Comment by BeauBouchard** [comment]
Have you tried to run DF without the package? 

Did you install the dependencies ? 

```
sudo apt-get install default-jre libsdl1.2debian:i386 libsdl-image1.2:i386 libsdl-ttf2.0-0:i386 libglu1-mesa:i386 libgtk2.0-0:i386 libopenal1:i386 libjpeg62:i386 git mercurial wget coreutils tar unzip unrar make g++ gcc patch xterm sed python bzip2 qtchooser qtbase5-dev qtbase5-dev-tools qtscript5-dev qt5-qmake libqt5script5 libqt5scripttools5 libqxt-core0 libqxt-gui0
```

I am running the LNP both on a Linux Mint 17 "Qiana" - Cinnamon (32-bit) fresh install and in a VM, There is no reason the application shouldn't be working to some capacity on your system if you followed these instructions.

**Comment by BeauBouchard** [comment]
I rebuilt a i686(32 bit) package on mint and uploaded it to the website. Try this package and let me know if it works or anything happens when you use it. 

http://www.lazynewbpack.com/linux/04016/download/i686/special_package.tar.gz

**Comment by Jay-Roden** [comment]
The package you rebuilt worked. _throws hand in the air with joy_

**Comment by BeauBouchard** [comment]
I am relieved that it is working for you, thank you again for taking the time to fill out an issues report. Enjoy DF.

**Comment by Grizmoblust** [comment]
I have the same issue on debian jessie. I tried running 64bit, and 32 bit. 

./PyLNP not found

**Comment by lethosor** [comment]
If "./PyLNP not found" is the complete error message, make sure you're running that in the right folder. If not, what distro are you using (and is it 32- or 64-bit)?

**Comment by Grizmoblust** [comment]
Debian Jessie. 64bit.

When I run ./startlnp, a new terminal opens up, then crashes. It says ./PyLNP not found.
It is inside of /pack/ folder.  I also tried outside of /pack/ folder, and did not work. 

I also tried compiling the qmake -qt=5 and it giving me an error, "it is a open directory." I tried compiling qmake-qt-5, command not found.

**Comment by ghost** [comment]
I am having the very same issue, and the links @BeauBouchard posted are not working already.

distro: lubuntu 17.10, 32bit
lnp version: LNP-Linux-legacy-0.40.24.r3.c454qt4

I can't even understand what this problem is about, and this is the only place on the internet where i found people discussing it.
I would be very grateful if someone could at least explain me whats wrong
