### ISSUE TITLE
Print Mode defaulting to TWBT... but TWBT not included

### ISSUE THREAD

**Issue by Ramblurr** [Lazy-Newb-Pack/LNP-Linux-legacy#8]
In the 40.16 release, the Print Mode default was set to TWBT, however TWBT isn't included (because there is no TWBT release for Linux@40.16).

**Comment by BeauBouchard** [comment]
Thanks for taking the time to post this issue, but this is not really an issue since this setting automatically reverts to defaults if there isnt TWBT. 

Are you having any errors as a result of this?

**Comment by Ramblurr** [comment]
Woop, sorry about that!
