### ISSUE TITLE
In my xubuntu 14.04 LNP does not work

### ISSUE THREAD

**Issue by vinniec** [Lazy-Newb-Pack/LNP-Linux-legacy#9]
I have installed all dependency and this is the output when I launch startlnp*http://sprunge.us/XhKR):

./PyLNP: 1: ./PyLNP: ýÿÿÿ%Ú!h: not found
./PyLNP: 1: ./PyLNP: NB]K: not found
./PyLNP: 1: ./PyLNP: FA_71X4:/: not found
./PyLNP: 1: ./PyLNP: ²ah²ap²ax²a²a²a²a: not found
./PyLNP: 2: ./PyLNP:  ²a
¨²a°²a¸²aÀ²aÈ²aÐ²aØ²aà²aè²að²aø²a³a³a³a³a: not found
./PyLNP: 1: ./PyLNP: ´aJh´aKp´aLx´aM´aN´aO´aP´aQ ´aR¨´aS°´aU¸´aVÀ´aWÈ´aXÐ´aYØ´aZà´a[è´a]ð´a^ø´a_µa: not found
./PyLNP: 1: ./PyLNP: ÿÿÿÿ%Ú!h: not found
./PyLNP: 2: ./PyLNP: é@ÿÿÿÿ%Ê!hé0ÿÿÿÿ%Â!hé: not found
./PyLNP: 1: ./PyLNP: cannot create @@xÀ@8@'$@@@@@ÀÀ@@@@Ô¯Ô¯ °°a°aà¨  ° °a °a@@DDPåtdì\ì\Aì\Aü
ü
Qåtd/lib64/ld-linux-x86-64.so.2GNU GNUc_­Å½5Ã}2~xÐ°É'¼CaYH56(T.QË 6Â_àµaÚØµaÞnÒå¡>ìÀIAÜZzðµaa@Øøp¦faíÐµa«úC½60ëJøµañYÍ©²[u¤Gaºñÿàµa+>n;ãtJË$f¶BÔ|0³ñÿàµa­ó¥ÁÇÆñÿ¨:b2T7libdl.so.2dlsymdlerrordlopenlibz.so.1inflateEndinflatezlibVersioninflateInit_libm.so.6sqrtlibc.so.6tolowergetenvfwritetouppermemcpystpcpyreallocvfprintfreadlinkstrcatfeofrealpathremovermdirstrcasecmpmkdtempmkdirmallocstrrchrstrlenopendir_IO_stdin_usedexecvstrncasecmpfdopensetbufwaitgetpidstdoutmemmovefclosefreadstrncatfopenfgetcstderrstrtok__libc_start_mainfilenovprintfclosedir__xpg_basenamefputcfgetsferrorstrncpyunsetenvunlinkfflushmemsetqsortmkstempmemcmpvsnprintfsprintfclearerrstdinfseekexitrenameforkraisestrstrstrcmpftellfreereaddirstrchrfchmodisspacestrdupntohlexecvpsignalstrcpykill__xstat_edata__bss_start_end__gmon_start__native_linker_pathlsb_linker_pathGLIBC_2.2.5GLIBC_2.3W ui ý ui    ýfii
   ui   ý ²a(²a0²aðµa8²a%àµaøµa.X²a³a(h³a)p³a_x³a+³a,³a-³a/³a0 ³a1¨³a2°³a3¸³a4À³a5È³a6Ð³a7Ø³a8à³a9è³a:ð³a<ø³a=´a>´a?´a@´aA ´aB(´aC0´aD8´aE@´aFH´aGP´aHX´aIHìè£HÄÃÿ5!ÿ%$!@ÿ%!héàÿÿÿÿ%!héÐÿÿÿÿ%!héÀÿÿÿÿ%
!hé°ÿÿÿÿ%!hé ÿÿÿÿ%ú!héÿÿÿÿ%ò!héÿÿÿÿ%ê!hépÿÿÿÿ%â!héþÿÿÿ%Z!héPþÿÿÿ%R!hé@þÿÿÿ%J!hé0þÿÿÿ%B!hé þÿÿÿ%:!héþÿÿÿ%2!héþÿÿÿ%_!héðýÿÿÿ%!h: Directory nonexistent
./PyLNP: 1: ./PyLNP: ELF: not found
./PyLNP: 8: ./PyLNP: Syntax error: "(" unexpected

**Comment by lethosor** [comment]
Looks like #7. Can you try the package linked to near the bottom?

**Comment by BeauBouchard** [comment]
Let me know if you still have the same issue with the [new packages.](http://www.lazynewbpack.com/linux/04019/)

 I also updated the 40.16 packs since then.
